# Generated by Django 6.0.5 on 2026-05-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guess_can_pause',
            new_name='guest_can_pause',
        ),
    ]
